//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("BooScriptExecutorFactory")]
[assembly: System.Reflection.AssemblyProduct("BooScriptExecutorFactory")]
[assembly: System.Reflection.AssemblyCopyright("Copyright 2008-2009 Sun Microsystems, Inc. All rights reserved.")]
[assembly: System.Reflection.AssemblyCompany("ForgeRock AS")]
[assembly: System.Reflection.AssemblyVersion("1.5.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.5.0.0")]


